apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scanco-system

resources:
- ../../base

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: scanco-webhook
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: webhook
            resources:
              limits:
                cpu: "500m"
                memory: "512Mi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DEVELOPMENT_MODE
              value: "true"
  target:
    kind: Deployment
    name: scanco-webhook 