apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scanco-system

resources:
- deployment.yaml
- webhook.yaml

commonLabels:
  app.kubernetes.io/name: scanco
  app.kubernetes.io/part-of: scanco-security

configMapGenerator:
- name: scanco-policy
  files:
  - policy.yaml=../../examples/policy.yaml 