apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: scanco-webhook
webhooks:
- name: scanco.security.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 30
  failurePolicy: Fail
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "Namespaced"
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: default
      name: scanco-webhook-svc
      path: "/validate"
      port: 443
    caBundle: ${CA_BUNDLE} 