name: test-policy
metadata:
  description: Test security policy for admission controller
  author: ScanCo
  version: "1.0"
rules:
  max_severity: MEDIUM
  blocked_cves:
    - CVE-2021-44228 # Log4Shell
    - CVE-2022-22965 # Spring4Shell
  allowed_base_images:
    - docker.io/library/alpine:latest
    - docker.io/library/ubuntu:22.04
  min_cvss: 7.0 