apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scanco-system

resources:
- ../../base

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: scanco-webhook
    spec:
      replicas: 3
      template:
        spec:
          containers:
          - name: webhook
            resources:
              limits:
                cpu: "1"
                memory: "1Gi"
              requests:
                cpu: "500m"
                memory: "512Mi"
  target:
    kind: Deployment
    name: scanco-webhook 